name: "Rust"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: "always"

jobs:
  build:

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - name: "Build"
        run: "cargo build --release --verbose"
      - name: "Run tests"
        run: "cargo test --verbose"
      
  publish:

      needs: "build"

      permissions:
        contents: "write"

      runs-on: "ubuntu-latest"

      steps:
        - uses: "marvinpinto/action-automatic-releases@v1.2.1"
          with:
            automatic_release_tag: "latest"
            files: "target/release/github-actions-test"
            prerelease: false
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
